CREATE TABLE customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT,
    amount DECIMAL(19,2),
    date DATE,
    CONSTRAINT fk_customer FOREIGN KEY (customer_id) REFERENCES customer(id)
); 